### ISSUE TITLE
Feature request: Translations

### ISSUE THREAD

**Issue by pleswi** [Jinjinov/Ididit#1]
Looks like a greate tool! But, I miss translations, because my parents and colleagues don't speak english :( Could you thinking about it? Thanks.

**Comment by Jinjinov** [comment]
I will look into it. What language would you like?

**Comment by pleswi** [comment]
I would like czech, but I think when you make lang file for translations, many users will translate their own language and send it like PR.

**Comment by Jinjinov** [comment]
I will add Slovenian, Croatian and German. When the translations are ready, you can add Czech :)

**Comment by Jinjinov** [comment]
Translations are progressing slowly. I have about 60% of the text translated to Slovenian and German.

**Comment by Jinjinov** [comment]
@pleswi Translations to Slovenian, German and Spanish are done :)

You can check them here: https://app.ididit.today/
